### ISSUE TITLE
Issue with MegaKeep hanging

### ISSUE THREAD

**Issue by snvoid** [maybecryptic/MegaKeep#3]
Using the latest version of megakeep and MEGAcmd on both Win 7 and Win 10 machines I'm having issues using the app. MegaKeep seems to do fine sometimes while logging in but then seems to hang when trying to log out and seems to be stuck. 

Only solution is to restart remove the emails that it hangs on and then run again. The problem doesn't seem to be with the email/passwords because it does in fact login, just seems to hang on logout, I confirmed this because I tried to rearrange the username/passwords and it worked fine on those logins and hangs again on other ones. However it seems completely arbitrary from my end on what causes it to hang. It's not like it does 6 logins and then fails each time.  It is entirely random. Sometimes 3, sometimes 8, sometimes 15, etc...

**Comment by xCryptic** [comment]
I've never ran into this issue before (I login to about 30 some accounts). I also recently upgraded to win10 and the functionality hasn't changed.

Though I've been using the same install for megacmd, so if they update it, I'm not getting those updates. It's possible they changed something in a newer version. My suggestion is to keep a megacmd window open while megakeep is running and see if anything pops up there or if it shows the account still logged in while it hangs.

**Comment by snvoid** [comment]
Thanks for the quick response xCryptic. Doesn't megacmd autoupdate? If not I might have to see if i can try an older version. I've tried to run it with the MegaCMDserver open as well as the megacmd open and I get no errors. It seems like the megacmdserver might be the one hanging. It seems to hang at the fetching nodes part. 

![hangs](https://user-images.githubusercontent.com/60519765/74205830-efa1c700-4c46-11ea-9a61-29be8994c092.jpg)

**Comment by xCryptic** [comment]
> Doesn't megacmd autoupdate?

I have no idea

> It seems to hang at the fetching nodes part.

I would suggest trying to logout of megacmd using the bat or the exe itself to see if that'll allow the rest to go through

> EDIT: Any way to add a stop and start button to megakeep that can let it continue starting with the next login on the list?

In theory, yes. I haven't been doing much C# lately so it'd take some research. It might also be possible to add a timer to check how long a process has been running and maybe go from there so you don't have to monitor it. But again, it'd take some time and my free time has lessened lately

**Comment by art-iszt** [comment]
> 
> 
> I've never ran into this issue before (I login to about 30 some accounts). I also recently upgraded to win10 and the functionality hasn't changed.
> 
> Though I've been using the same install for megacmd, so if they update it, I'm not getting those updates. It's possible they changed something in a newer version. My suggestion is to keep a megacmd window open while megakeep is running and see if anything pops up there or if it shows the account still logged in while it hangs.

maybe it is due to [any] additional notifications sent by mega when an account has overstretched its space limit or is -- as mega puts it -- running out of space ?

**Comment by xCryptic** [comment]
> an account has overstretched its space limit

I've got several accounts over by a gig or two, and many more close to the limit. this would be happening a lot more if that were the case

**Comment by Abu3safeer** [comment]
@snvoid  Try using a VPN on your machine, paid one would be better, it might be an issue with your internet. 
I had similar issues, using VPN gave me better results.
